name: Inthedepths
version: '${project.version}'
main: us.glasscrab.i.inthedepths.Inthedepths
api-version: 1.19
authors: [ glasscrab ]
description: Special items rarely spawning in certain locations of the world.
website: i.glasscrab.us
